#!/usr/bin/env node
// Assemble MCP-App widgets: for each widget/*.html, inline the ext-apps browser bundle +
// brand tokens, base64-encode, and emit app/_widgets.js exporting { <name>: b64, ... }.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const raw = readFileSync(join(ROOT, "vendor", "ext-apps-app-with-deps.js"), "utf8");

const bundle = raw.replace(/export\s*\{([^}]+)\}\s*;?\s*$/, (_, body) =>
  "globalThis.ExtApps={" +
  body.split(",").map((p) => {
    const [local, exported] = p.split(" as ").map((s) => s.trim());
    return `${exported ?? local}:${local}`;
  }).join(",") + "};"
);
if (bundle === raw) throw new Error("export-rewrite did not match -- bundle format changed");

const widgetDir = join(ROOT, "widget");
const brand = readFileSync(join(widgetDir, "brand.css"), "utf8");
const out = {};
const versions = {};
for (const f of readdirSync(widgetDir).filter((f) => f.endsWith(".html"))) {
  const name = basename(f, ".html");
  const html = readFileSync(join(widgetDir, f), "utf8")
    .replace("/*__BRAND__*/", () => brand)
    .replace("/*__EXT_APPS_BUNDLE__*/", () => bundle);
  out[name] = Buffer.from(html, "utf8").toString("base64");
  versions[name] = createHash("sha256").update(html).digest("hex").slice(0, 8);
  console.log(`  ${name}: ${html.length} bytes -> ${out[name].length} b64 . v${versions[name]}`);
}
writeFileSync(
  join(ROOT, "app", "_widgets.js"),
  `// AUTO-GENERATED by scripts/build-widget.mjs -- do not edit. Edit widget/*.html + rerun.\n` +
    `export const WIDGETS = ${JSON.stringify(out)};\n` +
    `export const WIDGET_VERSIONS = ${JSON.stringify(versions)};\n`
);
console.log(`built app/_widgets.js with: ${Object.keys(out).join(", ")}`);
